import { EnemyConfig } from '../config';

export const ENEMY_CONFIGS: { [key: string]: EnemyConfig } = {
    basicEnemy: {
        width: 25,
        height: 25,
        baseHealth: 50,
        baseDamage: 5,
        speed: 1,
        sprite: 'basic-enemy',
    },
    vampireHunter: {
        width: 25,
        height: 25,
        baseHealth: 50,
        baseDamage: 5,
        speed: 1,
        sprite: 'vampire-hunter',
        behavior: 'ranged',
    },
    fastSwarmer: {
        width: 18,
        height: 18,
        baseHealth: 20,
        baseDamage: 3,
        speed: 2.2,
        sprite: 'fast-swarmer',
        behavior: 'swarm',
    },
    tankyBrute: {
        width: 45,
        height: 45,
        baseHealth: 200,
        baseDamage: 10,
        speed: 0.5,
        sprite: 'tanky-brute',
    },
    silverMage: {
        width: 25,
        height: 25,
        baseHealth: 70,
        baseDamage: 8,
        speed: 1,
        sprite: 'silver-mage',
        behavior: 'ranged',
    },
    holyPriest: {
        width: 25,
        height: 25,
        baseHealth: 80,
        baseDamage: 3,
        speed: 0.8,
        sprite: 'holy-priest',
        behavior: 'healer',
    },
    vampireScout: {
        width: 20,
        height: 20,
        baseHealth: 40,
        baseDamage: 4,
        speed: 1.5,
        sprite: 'vampire-scout',
        behavior: 'summoner',
    },
};
